export const trackingConstant = {
    NEW_DELIVERY_REQUEST: 'NEW_DELIVERY_REQUEST',
    NEW_DELIVERY_FALIURE: 'NEW_DELIVERY_FALIURE',
    NEW_DELIVERY_SUCCESS: 'NEW_DELIVERY_SUCCESS',
    GETALL_DELIVERY_REQUEST: 'GETALL_DELIVERY_REQUEST',
    GETALL_DELIVERY_FALIURE: 'GETALL_DELIVERY_FALIURE',
    GETALL_DELIVERY_SUCCESS: 'GETALL_DELIVERY_SUCCESS',
    UPDATE_DELIVERY_REQUEST: 'UPDATE_DELIVERY_REQUEST',
    UPDATE_DELIVERY_FALIURE: 'UPDATE_DELIVERY_FALIURE',
    UPDATE_DELIVERY_SUCCESS: 'UPDATE_DELIVERY_SUCCESS',
    GETBY_ID_DELIVERY_REQUEST: 'GETBY_ID_DELIVERY_REQUEST',
    GETBY_ID_DELIVERY_FALIURE: 'GETBY_ID_DELIVERY_FALIURE',
    GETBY_ID_DELIVERY_SUCCESS: 'GETBY_ID_DELIVERY_SUCCESS',
};

export const paymentConstant = {
    NEW_PAYMENT_REQUEST: 'NEW_PAYMENT_REQUEST',
    NEW_PAYMENT_FALIURE: 'NEW_PAYMENT_FALIURE',
    NEW_PAYMENT_SUCCESS: 'NEW_PAYMENT_SUCCESS',
    GETALL_PAYMENT_REQUEST: 'GETALL_PAYMENT_REQUEST',
    GETALL_PAYMENT_FALIURE: 'GETALL_PAYMENT_FALIURE',
    GETALL_PAYMENT_SUCCESS: 'GETALL_PAYMENT_SUCCESS',
    UPDATE_PAYMENT_REQUEST: 'UPDATE_PAYMENT_REQUEST',
    UPDATE_PAYMENT_FALIURE: 'UPDATE_PAYMENT_FALIURE',
    UPDATE_PAYMENT_SUCCESS: 'UPDATE_PAYMENT_SUCCESS',
    GETBY_ID_PAYMENT_REQUEST: 'GETBY_ID_PAYMENT_REQUEST',
    GETBY_ID_PAYMENT_FALIURE: 'GETBY_ID_PAYMENT_FALIURE',
    GETBY_ID_PAYMENT_SUCCESS: 'GETBY_ID_PAYMENT_SUCCESS',
};
export const checkoutConstant = {
    NEW_CHECKOUT_REQUEST: 'NEW_CHECKOUT_REQUEST',
    NEW_CHECKOUT_FALIURE: 'NEW_CHECKOUT_FALIURE',
    NEW_CHECKOUT_SUCCESS: 'NEW_CHECKOUT_SUCCESS',
};